spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    az.qazan.backend: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
